const copy = {
  lv:{navAbout:'Par mums',navResources:'Digitālie resursi un rīki',navProjects:'Projekti',navTeam:'Komanda',navContact:'Kontakti',resourceTitle:'Digitālie resursi un rīki',teikasTitle:'Teikas',teikasDesc:'Digitāls resurss latviešu tautas teiku meklēšanai, analīzei un kartēšanai.',openTool:'Atvērt rīku',openResourceDev:'Atvērt resursu (izstrādē)',airaDesc:'Rīks rokraksta atšifrēšanai un attēlu aprakstīšanai ar mākslīgā intelekta palīdzību.',dhDesc:'Platforma ziņām, resursiem un projektiem digitālajās humanitārajās zinātnēs Latvijā.',viewSite:'Apskatīt vietni',address:'Visvalža iela 4a–207, Rīga, LV–1050',footerText:'LU Digitālo humanitāro zinātņu centrs, 2026'},
  en:{navAbout:'About us',navResources:'Digital resources and tools',navProjects:'Projects',navTeam:'Team',navContact:'Contacts',resourceTitle:'Digital resources and tools',teikasTitle:'Legends',teikasDesc:'A digital resource for searching, analysing and mapping Latvian folk legends.',openTool:'Open tool',openResourceDev:'Open resource (in development)',airaDesc:'A tool for transcribing handwriting and describing images with the help of artificial intelligence.',dhDesc:'A platform for news, resources and projects in digital humanities in Latvia.',viewSite:'Visit site',address:'Visvalža Street 4a–207, Riga, Latvia, LV–1050',footerText:'UL Digital Humanities Centre, 2026'}
};
let lang=location.hash.replace('#','')==='en'?'en':'lv',theme='light';
function apply(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=copy[lang][el.dataset.i18n]);document.getElementById('langToggle').textContent=lang==='lv'?'EN':'LV';document.getElementById('brandLogo').src=`assets/official-lu-${lang}-${theme==='dark'?'white':'black'}.png`;if(window.lucide)lucide.createIcons()}
document.getElementById('langToggle').onclick=()=>{lang=lang==='lv'?'en':'lv';history.replaceState(null,'',`#${lang}`);apply()};
document.getElementById('themeToggle').onclick=()=>{theme=theme==='dark'?'light':'dark';document.body.className=`resources-page theme-${theme}`;apply()};
const nav=document.getElementById('mainNav'),menu=document.getElementById('menuToggle');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const fontScales=[.92,1,1.14];let fontScaleIndex=Number(localStorage.getItem('dhc-font-scale')||1);function applyFontScale(){fontScaleIndex=Math.max(0,Math.min(fontScales.length-1,fontScaleIndex));document.documentElement.style.setProperty('--font-scale',fontScales[fontScaleIndex]);document.getElementById('fontDecrease').disabled=fontScaleIndex===0;document.getElementById('fontIncrease').disabled=fontScaleIndex===fontScales.length-1;localStorage.setItem('dhc-font-scale',fontScaleIndex)}document.getElementById('fontDecrease').onclick=()=>{fontScaleIndex--;applyFontScale()};document.getElementById('fontIncrease').onclick=()=>{fontScaleIndex++;applyFontScale()};
function buildNet(){const g=document.querySelector('.net-dots'),colors=['#a385ff','#d24bff','#7fb4ff','#ea6b9b'],pts=[];for(let r=0;r<16;r++)for(let c=0;c<16;c++){if(Math.random()>.7)continue;pts.push({x:c*50+25+(Math.random()-.5)*42,y:r*50+25+(Math.random()-.5)*42,c:colors[Math.floor(Math.random()*4)]})}let h='';pts.forEach((p,i)=>pts.slice(i+1).map(q=>({q,d:(p.x-q.x)**2+(p.y-q.y)**2})).sort((a,b)=>a.d-b.d).slice(0,2).forEach(({q,d})=>{if(d<9025)h+=`<line data-c x1="${p.x}" y1="${p.y}" x2="${q.x}" y2="${q.y}" style="color:${p.c};--peak:.25"/>`}));pts.forEach(p=>h+=`<circle data-c cx="${p.x}" cy="${p.y}" r="1.2" style="color:${p.c};opacity:.28"/>`);g.innerHTML=h}
function buildResourceDotArt(){const patterns={'visual-teikas':[26,27,28,29,34,35,36,37],'visual-aira':[3,4,11,12,19,20,27,28,35,36,43,44,51,52,59,60],'visual-dh':[9,14,18,21,27,28,35,36,42,45,49,54]};document.querySelectorAll('.resource-dot-art').forEach(art=>{const type=Object.keys(patterns).find(name=>art.classList.contains(name)),accents=new Set(patterns[type]||[]),fragment=document.createDocumentFragment();for(let index=0;index<64;index++){const dot=document.createElement('span');if(accents.has(index))dot.className='is-accent';fragment.appendChild(dot)}art.replaceChildren(fragment)})}
buildNet();buildResourceDotArt();applyFontScale();apply();
